article/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addArticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment"),  
] 

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


from article import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = "index"),
    path('about/',views.about,name = "about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/',views.register,name = "register"),
    path('login/',views.loginUser,name = "login"),
    path('logout/',views.logoutUser,name = "logout"),

]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Yazar ")
    title = models.CharField(max_length = 50,verbose_name = "Başlık")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    article_image = models.FileField(blank = True,null = True,verbose_name="Makaleye Fotoğraf Ekleyin")
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']
class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name = "Makale",related_name="comments")
    comment_author = models.CharField(max_length = 50,verbose_name = "İsim")
    comment_content = models.CharField(max_length = 200,verbose_name = "Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

user/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label = "Kullanıcı Adı")
    password = forms.CharField(label = "Parola",widget = forms.PasswordInput)


class RegisterForm(forms.Form):
    username = forms.CharField(max_length = 50,label = "Kullanıcı Adı")
    password = forms.CharField(max_length=20,label = "Parola",widget = forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label ="Parolayı Doğrula",widget = forms.PasswordInput)
    
    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Parolalar Eşleşmiyor")

        values = {
            "username" : username,
            "password" : password
        }
        return values

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from .models import Article,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.

def articles(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()

    return render(request,"articles.html",{"articles":articles})
def index(request):
    return render(request,"index.html")
    
def about(request):
    return render(request,"about.html")
@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles":articles
    }
    return render(request,"dashboard.html",context)
@login_required(login_url = "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        
        article.author = request.user
        article.save()

        messages.success(request,"Makale başarıyla oluşturuldu")
        return redirect("article:dashboard")
    return render(request,"addarticle.html",{"form":form})
def detail(request,id):
    #article = Article.objects.filter(id = id).first()   
    article = get_object_or_404(Article,id = id)

    comments = article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})
@login_required(login_url = "user:login")
def updateArticle(request,id):

    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance = article)
    if form.is_valid():
        article = form.save(commit=False)
        
        article.author = request.user
        article.save()

        messages.success(request,"Makale başarıyla güncellendi")
        return redirect("article:dashboard")


    return render(request,"update.html",{"form":form})
@login_required(login_url = "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)

    article.delete()

    messages.success(request,"Makale Başarıyla Silindi")

    return redirect("article:dashboard")
def addComment(request,id):
    article = get_object_or_404(Article,id = id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author  = comment_author, comment_content = comment_content)

        newComment.article = article

        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))
    

user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout



# Create your views here.

def register(request):

    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        newUser = User(username =username)
        newUser.set_password(password)

        newUser.save()
        login(request,newUser)
        messages.info(request,"Başarıyla Kayıt Oldunuz...")

        return redirect("index")
    context = {
            "form" : form
        }
    return render(request,"register.html",context)

    
    
def loginUser(request):
    form = LoginForm(request.POST or None)

    context = {
        "form":form
    }

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username,password = password)

        if user is None:
            messages.info(request,"Kullanıcı Adı veya Parola Hatalı")
            return render(request,"login.html",context)

        messages.success(request,"Başarıyla Giriş Yaptınız")
        login(request,user)
        return redirect("index")
    return render(request,"login.html",context)
def logoutUser(request):
    logout(request)
    messages.success(request,"Başarıyla Çıkış Yaptınız")
    return redirect("index")

templates/about.html
{% extends "layout.html" %}


{% block body %}


<div style="margin-top :15px;"class=" container my-3 p-3 bg-white rounded shadow-lg">
    <h6 style="font-size:25px;" class="border-bottom border-gray pb-2 mb-0">Dogardo Kimdir?</h6>
    <div class="media text-muted pt-3">
      
      <p style="font-size:15px;"class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
       
       İsmim Doğa Arda Gaval. 2017 yılında Prof.Dr Fuat Sezgin Fen Lisesi'nden mezun olduktan sonra
       Tekirdağ Namık Kemal Üniversitesi Mimarlık bölümüne yerleştim. 2019-2020 Yarıyılında okuduğum okulu beğenmeyip bıraktım. 2020
       yılında ise Yıldız Teknik Üniversitesi Mimarlık bölümüne tekrardan yerleştim. Kodlama ve tasarım alanına olan ilgimden dolayı
       kendime bir portfolyo oluşturup, yaptığım işleri burada sergilemek ve ilgisi olanlara yapıtlarımı satmak adına bu forumu açtım.
       Yaptığım işleri daha detaylı incelemek için sağ üst köşedeki çalışmalarım sekmesine girip kurcalama yapabilirsiniz.</p>
    </div>


    <small class="d-block text-right mt-3">
    </small>
  </div>
  

  <div style="margin-top :15px;"class="container my-3 p-3 bg-white rounded shadow-lg">
    <h6 style="font-size:25px;" class="border-bottom border-gray pb-2 mb-0">Mimarlık Adına</h6>

      <div class="media text-muted pt-3">
        <li style="font-size:15px;"class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          Autocad
        </li>
      </div>

      <div class="media text-muted pt-3">
        <li style="font-size:15px;"class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          Revit
        </li>
      </div>

      <div class="media text-muted pt-3">
        <li style="font-size:15px;"class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          Rhinoceros
        </li>

      </div>
      
      
      <div class="media text-muted pt-3">
        <li style="font-size:15px;"class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          SketchUp
        </li>

      </div>
      
 


    <small class="d-block  mt-3">
           <p style="font-size:15px;"class="media-body pb-3 mb-0 small lh-125 text-muted border-bottom border-gray">
       
       Sketchup'ı basit kütle çalışmaları, Revit'i organik form düzenlemeleri, kesit-görünüş-kat ve tavan-vaziyet planları çıkarımı
        için kullanırken Rhinoceros'u; Revit'te çıkaramadığım organik formları tasarlayıp Revitten tanımlamak 
         , Autocad'i ise diğer programlardan tasarladığım eserleri paftalamak ve çıktı haline getirmek için kullanmaktayım.</p>
    
  </div>
 


  <div style="margin-top :15px;"class="container my-3 p-3 bg-white rounded shadow-lg">
    <h6 style="font-size:25px;" class="border-bottom border-gray pb-2 mb-0">Görsel Tasarım Adına</h6>

      <div class="media text-muted pt-3">
        <li style="font-size:15px;"class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          Photoshop CS6
        </li>
      </div>


        <small class="d-block  mt-3">
           <p style="font-size:15px;"class="media-body pb-3 mb-0 small lh-125 text-muted border-bottom border-gray">
       
       Photoshop programını tasarladığım logoların ve dövmelerin renklendirmesi, mimarlık alanında ise sunum paftası tasarımında
       kullanmaktayım. 
       
        </p>
    </small>
  </div>


  <div style="margin-top :15px;"class=" container my-3 p-3 bg-white rounded shadow-lg">
    <h6 style="font-size:25px;" class="border-bottom border-gray pb-2 mb-0">Yazılım Adına</h6>

      <div class="media text-muted pt-3">
        <li style="font-size:15px;"class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          Python
        </li>
      </div>

      <div class="media text-muted pt-3">
        <li style="font-size:15px;"class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          Django (Web Framework for Python)
        </li>
      </div>

      <div class="media text-muted pt-3">
        <li style="font-size:15px;"class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          Flask (Web Framework for Python)
        </li>
      </div>

      <div class="media text-muted pt-3">
        <li style="font-size:15px;"class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          HTML+CSS
        </li>
      </div>


        <small class="d-block  mt-3">
           <p style="font-size:15px;"class="media-body pb-3 mb-0 small lh-125 text-muted border-bottom border-gray">
       
        Bu programları birbirleriyle entegre olacak şekilde web tasarımı adına kullanmaktayım. Flask'ı çok fazla kullanmasam da
        Django üzerinden tasarladığım birden fazla web sitesi var. Linklerini ise çalışmalar kısmındaki web tasarımlarım sekmesinden bulabilirsiniz.
       
        </p>
    </small>
  </div>
  



{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Oluştur</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Makale Ekle</button>
        </form>
    </div>
  </div>


{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}




<div class="navbar navbar-expand-lg navbar-light shadow-lg container rounded" style="margin-top :15px;">
<div class="navbar-collapse collapse" id="navbarsExample09" style="false">

      <ul class="navbar-nav text-center" style = "margin-left: 5px;">
      
      
<li ><a class="nav-link" href="/articles/?keyword=%28dövme%29">Dövme</a></li>
<li><a class="nav-link" href="/articles/?keyword=%28logo%29">Logo</a></li>
<li><a class="nav-link" href="/articles/?keyword=%28website%29">Website</a></li>
<li><a class="nav-link" href="/articles/?keyword=%28mimari%29">Mimari</a></li>
      </ul>
</div>
</div>
{% if articles %}

{% for article in articles %}


<div style="margin-top :15px;"class="shadow-lg my-3 p-3 bg-white rounded shadow-sm container">

{% if article.article_image %}
      <hr>
      <a href="{% url 'article:detail' article.id %}" class=""><img class=" img-fluid rounded" style="display: block;margin-left: auto;margin-top: 25px;margin-bottom: 25px;margin-right: auto;" width="500" src="{{article.article_image.url}}" alt=""></a>
      
{% endif %}

 
    <h6 style="font-size:30px;margin-top:15px" class="  pb-2 mb-0"><a href="{% url 'article:detail' article.id %}" class="text-muted text-center" ><h2 style="font-size:30px;"class="">{{article.title}}</h2></a> </h6>
   <hr>
        <p style="font-size:20px; margin-top:15px"class="media-body pb-3 mb-0 small lh-125 text-muted">
           Açıklama: (Kod-{{article.id}}) <p style="font-size:12px; margin-top:10px" >{{article.content|safe|truncatewords:10}}</p>
      
    

    
    
    <a style ="float : right;" href="{% url 'article:detail' article.id %}" class ="btn btn-danger">Devamını Oku</a>
  
<br><br>
 <hr>  
        <small class="d-block  mt-3">

    </small>
   
    <p style="font-size:12px; margin-top:10px;" class="media-body pb-3 mb-0 small lh-125 text-muted text-right">
           Eserin Siteye Eklenme Tarihi: {{article.created_date}}
    </p>
  </div>
  
{% endfor %}

{% else %}


{% endif %}




{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>Kontrol Paneli</h3>
<hr>
<p>
    Hoşgeldiniz, <small>{{request.user.username}}</small>
</p>
<hr>
<a class = "btn btn-danger" href = "{% url 'article:addarticle' %}">Makale Ekle </a>
<hr>
{% if articles %}
<table class="table">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Başlık</th>
            <th scope="col">Yazar</th>
            <th scope="col">Tarih</th>
            <th scope="col">Güncelle</th>
            <th scope="col">Sil</th>
          </tr>
        </thead>
        <tbody>
          {% for article in articles %}
          <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.created_date}}</td>
            <td><a href="{% url 'article:update' article.id %}" class = "btn btn-danger">Güncelle</a></td>
            <td><a href="{% url 'article:delete' article.id %}" class = "btn btn-danger">Sil</a> </td>
              
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
{% else %}

<div class = "alert alert-danger">
    Henüz bir makaleniz bulunmuyor...

</div>
{% endif %}



{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}
<div class="container">
<div class="row ">

<div  style="" class="container-sm  p-3 bg-white rounded shadow-lg col-3">
    

        <p style="; font-size:10px;"class="media-body pb-3 mb-0 small lh-125 text-muted border-bottom border-gray " >Oluşturulma Saati: {{article.created_date}}</p>
        <small class="d-block  mt-3">
        
          {% if article.article_image %}
          
          <div class=" rounded" >
          <a class="block right"><img class=" img-fluid rounded center block" style="center background-size: cover;margin-top: 25px;margin-bottom: 25px;margin-left:auto;margin-right:auto;" width="270" src="{{article.article_image.url}}" alt=""></a>
        </div> <hr>{% endif %}
           <p style="margin-top :15px; font-size:15px;"class="media-body pb-3 mb-0 small lh-125 text-muted border-bottom border-gray " >{{article.title}}</p>
           <p style="margin-top :15px; font-size:15px;"class="media-body pb-3 mb-0 small lh-125 text-muted border-bottom border-gray " >Kod: {{article.id}}</p>
           <p style="margin-top :15px; font-size:15px;"class="media-body pb-3 mb-0 small lh-125 text-muted border-bottom border-gray " >Eser Sahibi: {{article.author.username}}</p>
           
        </small>
</div> 
 

          <div  style="" class="container-sm  p-3 bg-none rounded col">

        </div> 


            <div  style="" class="container-sm  p-3 bg-white rounded shadow-lg col-8">
    


        <small class="d-block  mt-3">
        
          <p style="margin-top :15px; font-size:20px;"class="media-body pb-3 mb-0 small lh-125 text-muted" >Açıklama:</p>
          <hr>
          <p style="margin-top :0px; font-size:15px;"class="media-body pb-3 mb-0 small lh-125 text-muted" >{{article.content|safe}}</p>
        
        </small>
        
     </div> 
      




  </div></div>

<br>
{% endblock body %}

templates/includes/footer.html
<div class="container  p-3 bg-white rounded shadow-lg" style=" " >
  

  <div style="  margin-top :px;"class=" media ">

      
        
          <a target="_blank" rel="noopener noreferrer" style="margin-left:5px;" href="https://api.whatsapp.com/send?phone=905380618677"><img target="_blank" rel="noopener noreferrer" href="https://api.whatsapp.com/send?phone=905380618677"src="../media/WHATSAPP.png" width="35"></a>
          <p></p>
          <br>
          <a target="_blank" rel="noopener noreferrer" style="margin-left:25px;" href="https://www.instagram.com/dogardo/"><img target="_blank" rel="noopener noreferrer" href="https://www.instagram.com/dogardo/"src="../media/İNSTAGRAM.png" width="35"></a>
          <a target="_blank" rel="noopener noreferrer"  style="margin-left:25px;" href="https://www.twitter.com/thedogardo/"><img target="_blank" rel="noopener noreferrer" href="https://www.twitter.com/thedogardo/"src="../media/twitter.png" width="35"></a>


        <small class="d-block  mt-3">
           <p style="font-size:15px;"class="media-body pb-3 mb-0 small lh-125 text-muted ">

        </p>
    </small>
</div>
  </div>
 

templates/includes/navbar.html
<nav class="container rounded navbar navbar-expand-lg navbar-light shadow-lg" style="">
   
          <button style = "margin-top: px;margin-t-bot:px; " class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    


    <div class="navbar-collapse collapse" id="navbarsExample09" style="margin-top:-5px;">
   
      <ul class="navbar-nav mr-auto" style = "margin-left: px;">
      <li><a  href="/" style = "margin-left:5px;" class=" nav-link "><img target="_blank" rel="noopener noreferrer" href="/"src="../media/logox.png" width="80"></a> </li>
      
      <li><a  href="/" style = "font-size:18px;margin-top:4px ; color:black;" class=" nav-link text-center">DOGARDO</a> </li>
      

  

      </ul>
      

    
      <ul class="navbar-nav  " style = "">


        <li class="nav-item ">
        <li><a class="nav-link text-center" href="/">Anasayfa</a></li>
        <li><a class="nav-link text-center" href="{% url 'about'  %}">Hakkımda</a></li>
        
        <li><a class="nav-link text-center" href="/articles">Çalışmalarım</a></li>
    
        </li>
      </ul>
       
    </div>


  </nav>

templates/includes/posttemplate.html
<div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h1 class="mt-4">Post Title</h1>

      <!-- Author -->
      <p class="lead">
        by
        <a href="#">Start Bootstrap</a>
      </p>

      <hr>

      <!-- Date/Time -->
      <p>Posted on January 1, 2018 at 12:00 PM</p>

      <hr>

      <!-- Preview Image -->
      <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

      <hr>

      <!-- Post Content -->
      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

      <blockquote class="blockquote">
        <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
        <footer class="blockquote-footer">Someone famous in
          <cite title="Source Title">Source Title</cite>
        </footer>
      </blockquote>

      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

      <hr>

      <!-- Comments Form -->
      <div class="card my-4">
        <h5 class="card-header">Leave a Comment:</h5>
        <div class="card-body">
          <form>
            <div class="form-group">
              <textarea class="form-control" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>

      <!-- Single Comment -->
      <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
          <h5 class="mt-0">Commenter Name</h5>
          Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
        </div>
      </div>

      <!-- Comment with nested comments -->
      <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
          <h5 class="mt-0">Commenter Name</h5>
          Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

          <div class="media mt-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
          </div>

          <div class="media mt-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
          </div>

        </div>
      </div>

    </div>

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Search Widget -->
      <div class="card my-4">
        <h5 class="card-header">Search</h5>
        <div class="card-body">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-secondary" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>

      <!-- Categories Widget -->
      <div class="card my-4">
        <h5 class="card-header">Categories</h5>
        <div class="card-body">
          <div class="row">
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <a href="#">Web Design</a>
                </li>
                <li>
                  <a href="#">HTML</a>
                </li>
                <li>
                  <a href="#">Freebies</a>
                </li>
              </ul>
            </div>
            <div class="col-lg-6">
              <ul class="list-unstyled mb-0">
                <li>
                  <a href="#">JavaScript</a>
                </li>
                <li>
                  <a href="#">CSS</a>
                </li>
                <li>
                  <a href="#">Tutorials</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <!-- Side Widget -->
      <div class="card my-4">
        <h5 class="card-header">Side Widget</h5>
        <div class="card-body">
          You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
        </div>
      </div>

    </div>

  </div>

templates/login.html
{% extends "layout.html" %}
{% block body %}


{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}



{% endblock body %}

templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Güncelle</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Makale Güncelle</button>
        </form>
    </div>
  </div>


{% endblock body %}